version: "3"

services:
  postgres:
    restart: unless-stopped
    container_name: postgres
    image: postgres:12.0-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=chernobyl
      - POSTGRES_USER=remi
      - POSTGRES_PASSWORD=nicolas69700
    networks:
      - nginx-proxy

  backend:
    restart: unless-stopped
    container_name: backend
    build: ./
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static:/var/www/backend/static
      - ./media:/var/www/backend/media
    expose:
      - 8000
    env_file: ./.env
    depends_on:
      - postgres
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
    name: nginx-proxy

volumes:
  static:
  media:
  postgres: