version: "3.6"

services:
  db:
    restart: unless-stopped
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - nginx-proxy

  backend:
    container_name: backend-chernobyl
    restart: unless-stopped
    build: ./backend/
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./log/:/usr/src/core
      - static:/var/www/chernobyl/backend/assets
      - media:/var/www/chernobyl/backend/media
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
    name: nginx-proxy

volumes:
  postgres_data:
  static:
  media:
