version: "3.5"

services:
  postgres:
    container_name: postgres
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./.env
    networks:
      - nginx-proxy
  backend:
    container_name: backend
    restart: unless-stopped
    build: ./
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - ./log/:/usr/src/core
      - static:/var/www/chernobyl/backend/assets
      - media:/var/www/chernobyl/backend/media
    expose:
      - 8000
    env_file: ./.env
    networks:
      - nginx-proxy
    depends_on:
      - postgres

networks:
  nginx-proxy:
    external: true
    name: nginx-proxy

volumes:
  static:
  media:
  postgres_data: