# Generated by Django 3.1.1 on 2020-09-30 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='common.Tag')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'Français')], max_length=4)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langs', to='timeline.event')),
            ],
            options={
                'ordering': ['language', '-id'],
                'abstract': False,
            },
        ),
    ]
