# Generated by Django 3.0.8 on 2020-08-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_squashed_0003_auto_20200815_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelang',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='documentlang',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='picturelang',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videolang',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
