# Generated by Django 3.0.8 on 2020-07-26 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='articlelang',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='articlelang',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='document',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='documentlang',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='documentlang',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='event',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='eventlang',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='eventlang',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='picturelang',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='picturelang',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='video',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='video',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='videolang',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='videolang',
            name='updated',
        ),
        migrations.AlterField(
            model_name='article',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='timeline.Event'),
        ),
        migrations.AlterField(
            model_name='document',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='timeline.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='timeline.Event'),
        ),
        migrations.AlterField(
            model_name='video',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='timeline.Event'),
        ),
    ]
