# Generated by Django 3.1.1 on 2020-09-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AddField(
            model_name='event',
            name='have_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='have_minutes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='have_seconds',
            field=models.BooleanField(default=False),
        ),
    ]
