# Generated by Django 3.1.1 on 2020-09-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20200922_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='eventlang',
            options={'ordering': ['language', '-id']},
        ),
    ]
