# Generated by Django 3.0.8 on 2020-08-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_people_tags'),
        ('timeline', '0002_auto_20200810_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='article', to='common.Tag'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='document', to='common.Tag'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='picture', to='common.Tag'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='video', to='common.Tag'),
        ),
    ]
