# Generated by Django 3.1.1 on 2020-09-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20200930_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='have_hours',
            new_name='have_hour',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='have_minutes',
            new_name='have_minute',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='have_seconds',
            new_name='have_second',
        ),
    ]
