# Generated by Django 3.0.8 on 2020-07-31 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20200729_1439'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='article',
            name='article_extra_article',
        ),
        migrations.RemoveConstraint(
            model_name='video',
            name='video_extra_video',
        ),
        migrations.AlterField(
            model_name='article',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_event', to='timeline.Event'),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_event', to='timeline.Event'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picture_event', to='timeline.Event'),
        ),
        migrations.AlterField(
            model_name='video',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_event', to='timeline.Event'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.URLField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set(),
        ),
    ]
