# Generated by Django 3.1.1 on 2020-09-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20200930_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id']},
        ),
    ]
