# Generated by Django 3.0.8 on 2020-08-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20200731_1610'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='articlelang',
            name='articlelang_unique',
        ),
        migrations.RemoveConstraint(
            model_name='documentlang',
            name='documentlang_unique',
        ),
        migrations.RemoveConstraint(
            model_name='eventlang',
            name='eventlang_unique',
        ),
        migrations.RemoveConstraint(
            model_name='picturelang',
            name='picturelang_unique',
        ),
        migrations.RemoveConstraint(
            model_name='videolang',
            name='videolang_unique',
        ),
        migrations.AlterUniqueTogether(
            name='articlelang',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='documentlang',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='eventlang',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='picturelang',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='videolang',
            unique_together=set(),
        ),
    ]
