# Generated by Django 3.0.8 on 2020-09-05 17:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20200825_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2020, 9, 5, 17, 56, 45, 381596, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
