# Generated by Django 3.1.1 on 2020-09-21 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timeline', '0001_squashed_0003_auto_20200921_1039'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_auto_20200921_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('born', models.DateField(blank=True, null=True)),
                ('death', models.DateField(blank=True, null=True)),
                ('profil', models.ImageField(blank=True, null=True, upload_to=gallery.models.profil_path)),
                ('wikipedia', models.URLField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_creator', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='peoples', to='common.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('picture', models.ImageField(upload_to=gallery.models.picture_path)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picture_creator', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='timeline.event')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='gallery.people')),
                ('tags', models.ManyToManyField(blank=True, related_name='picture', to='common.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('video', models.URLField(unique=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_creator', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='timeline.event')),
                ('tags', models.ManyToManyField(blank=True, related_name='video', to='common.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'Français')], default='en', max_length=4)),
                ('title', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videolang_creator', to=settings.AUTH_USER_MODEL)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langs', to='gallery.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PictureLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'Français')], default='en', max_length=4)),
                ('title', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picturelang_creator', to=settings.AUTH_USER_MODEL)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langs', to='gallery.picture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeopleLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'Français')], default='en', max_length=4)),
                ('biography', models.TextField()),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peoplelang_creator', to=settings.AUTH_USER_MODEL)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langs', to='gallery.people')),
            ],
            options={
                'ordering': ['language'],
                'abstract': False,
            },
        ),
    ]
