# Generated by Django 3.1.1 on 2020-09-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplelang',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français')], max_length=4),
        ),
        migrations.AlterField(
            model_name='picturelang',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français')], max_length=4),
        ),
        migrations.AlterField(
            model_name='videolang',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français')], max_length=4),
        ),
    ]
