# Generated by Django 3.1.1 on 2020-10-01 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        ('timeline', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='timeline.event'),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='video', to='common.Tag'),
        ),
        migrations.AddField(
            model_name='picturelang',
            name='extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langs', to='gallery.picture'),
        ),
        migrations.AddField(
            model_name='picture',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='timeline.event'),
        ),
        migrations.AddField(
            model_name='picture',
            name='photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='gallery.people'),
        ),
        migrations.AddField(
            model_name='picture',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='picture', to='common.Tag'),
        ),
        migrations.AddField(
            model_name='peoplelang',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langs', to='gallery.people'),
        ),
        migrations.AddField(
            model_name='people',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='peoples', to='common.Tag'),
        ),
    ]
