# Generated by Django 3.1.1 on 2020-09-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200922_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='peoplelang',
            options={'ordering': ['language', '-id']},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='picturelang',
            options={'ordering': ['language', '-id']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='videolang',
            options={'ordering': ['language', '-id']},
        ),
        migrations.AlterField(
            model_name='people',
            name='wikipedia',
            field=models.URLField(null=True),
        ),
    ]
