# Generated by Django 3.1.1 on 2020-10-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20201001_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplelang',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch'), ('it', 'Italiano'), ('es', 'Español'), ('uk', 'Українська'), ('ru', 'русский'), ('zh', '漢語'), ('ja', '日本語 (にほんご)')], max_length=4),
        ),
        migrations.AlterField(
            model_name='picturelang',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch'), ('it', 'Italiano'), ('es', 'Español'), ('uk', 'Українська'), ('ru', 'русский'), ('zh', '漢語'), ('ja', '日本語 (にほんご)')], max_length=4),
        ),
        migrations.AlterField(
            model_name='videolang',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch'), ('it', 'Italiano'), ('es', 'Español'), ('uk', 'Українська'), ('ru', 'русский'), ('zh', '漢語'), ('ja', '日本語 (にほんご)')], max_length=4),
        ),
    ]
