# Generated by Django 3.1.1 on 2020-09-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200930_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.AddField(
            model_name='video',
            name='have_hour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='have_minute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='have_second',
            field=models.BooleanField(default=False),
        ),
    ]
