# Generated by Django 3.1.1 on 2020-09-30 18:46

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20200930_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='profil',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.profil_path),
        ),
        migrations.AlterField(
            model_name='people',
            name='wikipedia',
            field=models.URLField(blank=True, null=True),
        ),
    ]
