# Generated by Django 3.1.1 on 2020-10-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20201009_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='wikipedia',
        ),
    ]
