# Generated by Django 3.1.1 on 2020-10-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_people_wikipedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='photographer',
        ),
    ]
