# Generated by Django 3.1.1 on 2020-10-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_news_is_active'),
        ('gallery', '0008_auto_20201015_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterlang',
            old_name='people',
            new_name='character',
        ),
        migrations.AlterField(
            model_name='character',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='characters', to='common.Tag'),
        ),
    ]
