# Generated by Django 3.0.8 on 2020-08-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='uuid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='issue',
            name='uuid',
            field=models.CharField(max_length=200),
        ),
    ]
