# Generated by Django 3.1.1 on 2020-09-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translatelang',
            options={},
        ),
        migrations.AlterField(
            model_name='taglang',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français')], max_length=4),
        ),
        migrations.AlterField(
            model_name='translate',
            name='key',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='translatelang',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français')], max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='translatelang',
            unique_together={('parent_key', 'language')},
        ),
    ]
