# Generated by Django 3.1.1 on 2020-09-21 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_squashed_0007_auto_20200921_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='translatelang',
            name='parent_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langs', to='common.translate'),
        ),
    ]
