# Generated by Django 3.1.1 on 2020-09-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200922_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='taglang',
            options={'ordering': ['language', '-id']},
        ),
        migrations.AlterModelOptions(
            name='translate',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='translatelang',
            options={'ordering': ['-id']},
        ),
    ]
