# Generated by Django 3.0.8 on 2020-08-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200812_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='uuid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='uuid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
