# Generated by Django 3.0.8 on 2020-07-30 12:15

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0003_auto_20200729_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'Français')], default='en', max_length=4)),
                ('biography', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='taglang',
            name='taglang_sunique',
        ),
        migrations.AddField(
            model_name='people',
            name='born',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='profil',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=common.models.profil_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='wikipedia',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='taglang',
            unique_together={('language', 'tag')},
        ),
        migrations.AddConstraint(
            model_name='taglang',
            constraint=models.UniqueConstraint(fields=('language', 'tag'), name='taglang_unique'),
        ),
        migrations.AddField(
            model_name='peoplelang',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peoplelang_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peoplelang',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langs', to='common.People'),
        ),
    ]
