# Generated by Django 3.0.8 on 2020-08-15 10:40

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200812_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='profil',
            field=models.ImageField(blank=True, null=True, upload_to=common.models.profil_path),
        ),
    ]
