# Generated by Django 3.0.8 on 2020-07-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200730_1215'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='peoplelang',
            unique_together={('language', 'people')},
        ),
        migrations.AddConstraint(
            model_name='peoplelang',
            constraint=models.UniqueConstraint(fields=('language', 'people'), name='peoplelang_unique'),
        ),
    ]
