# Generated by Django 3.1.1 on 2020-09-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200919_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translatelang',
            old_name='key',
            new_name='parent_key',
        ),
    ]
