# Generated by Django 3.0.8 on 2020-08-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200815_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='peoples', to='common.Tag'),
        ),
    ]
