# Generated by Django 3.1.1 on 2020-10-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date', 'title']},
        ),
    ]
