# Generated by Django 3.1.1 on 2020-10-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
