# Generated by Django 3.1.1 on 2020-10-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch'), ('it', 'Italiano'), ('es', 'Español'), ('uk', 'Українська'), ('ru', 'русский'), ('zh', '漢語'), ('ja', '日本語 (にほんご)')], default='en', max_length=4),
        ),
        migrations.AddField(
            model_name='user',
            name='show_help',
            field=models.BooleanField(default=True),
        ),
    ]
