# Generated by Django 3.1.1 on 2020-10-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_show_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='show_help',
            new_name='show_helpers',
        ),
    ]
