# Generated by Django 3.1.1 on 2020-09-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='updated_field',
            new_name='updated_fields',
        ),
    ]
