# Generated by Django 3.1.1 on 2020-09-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20200923_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commit',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-id']},
        ),
    ]
